[workspace]

members = [
    "apps/engine.svc.api.namora.ai",
    "apps/task-orchestrator.svc.api.namora.ai",
    "apps/user-socket.svc.api.namora.ai",
    "libs/engine_db_repository",
    "libs/namora_core",
    "functions/upsert-indexes-pinecone"
]