[workspace]

members = [
    "apps/engine-service",
    "apps/chat-user-worker",
    "apps/chat-ai-worker",
    "apps/chat-system-worker",
    "libs/agent_db_repository",
    "libs/engine_db_repository",
]