[workspace]

members = [
    "apps/engine-service",
    "apps/task-orchestrator-service",
    "apps/user-socket-service",
    "libs/engine_db_repository",
    "libs/namora_core",
    "functions/upsert-indexes-pinecone"
]