apiVersion: v1
kind: Service
metadata:
  name: task-orchestrator-service-service
  labels:
    name: task-orchestrator-service-service
spec:
  type: ClusterIP
  selector:
    name: task-orchestrator-service-pod
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000