apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-service-deployment
  labels:
    name: engine-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: engine-service-pod
  template:
    metadata:
      name: engine-service-pod
      labels:
        name: engine-service-pod
    spec:
      containers:
        - name: engine-service-pod
          image: 538780007699.dkr.ecr.us-west-2.amazonaws.com/engine-service:0ffa6bccd328eacdd95a8d0f3e31bd76adb637fa
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          envFrom:
          - secretRef:
              name: namora-secrets