apiVersion: v1
kind: Service
metadata:
  name: web-console-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:538780007699:certificate/4c46f772-7314-4d08-94f5-6ed8874a3a1a
  labels:
    name: web-console-service
spec:
  type: LoadBalancer
  selector:
    name: web-console-pod
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000